// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwOW6WlhQLdAJtMjtp8zqi6O1xeB-AC4',
    appId: '1:330408001016:web:a352f39f73a54a52edea0d',
    messagingSenderId: '330408001016',
    projectId: 'my-todo-4dcbe',
    authDomain: 'my-todo-4dcbe.firebaseapp.com',
    storageBucket: 'my-todo-4dcbe.firebasestorage.app',
    measurementId: 'G-45FWTG2QG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokIYNnBTNt1YE2EPYw_dhd6OtUv9rtdc',
    appId: '1:330408001016:android:3cf2982358c850c8edea0d',
    messagingSenderId: '330408001016',
    projectId: 'my-todo-4dcbe',
    storageBucket: 'my-todo-4dcbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNJwnIpy5KK10TgYQfo_mDJIQBdzceyk',
    appId: '1:330408001016:ios:fdd3cbc6da8638caedea0d',
    messagingSenderId: '330408001016',
    projectId: 'my-todo-4dcbe',
    storageBucket: 'my-todo-4dcbe.firebasestorage.app',
    iosBundleId: 'com.example.myTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNJwnIpy5KK10TgYQfo_mDJIQBdzceyk',
    appId: '1:330408001016:ios:fdd3cbc6da8638caedea0d',
    messagingSenderId: '330408001016',
    projectId: 'my-todo-4dcbe',
    storageBucket: 'my-todo-4dcbe.firebasestorage.app',
    iosBundleId: 'com.example.myTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwOW6WlhQLdAJtMjtp8zqi6O1xeB-AC4',
    appId: '1:330408001016:web:2b8e82ae4ccd1478edea0d',
    messagingSenderId: '330408001016',
    projectId: 'my-todo-4dcbe',
    authDomain: 'my-todo-4dcbe.firebaseapp.com',
    storageBucket: 'my-todo-4dcbe.firebasestorage.app',
    measurementId: 'G-6HTPF33063',
  );
}
